#!/usr/bin/env sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv='mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)' \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f='$FILE' \
	g="git" \
	trem="transmission-remote" \
	e='$EDITOR' \
	v='$EDITOR' \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"

### tmux
alias tmux="tmux -u"

### editors
alias emacs="emacs -nw"

alias vi="vim"

### languages
alias lisp="sbcl"

### toolchains
alias make='make -j$(nproc) --debug=n'

### pacman/yay
# pacman
alias pacin="sudo pacman -S"
alias pacins="sudo pacman -U"
alias pacinsd="sudo pacman -S --asdeps"
alias pacloc="pacman -Qi"
alias paclocs="pacman -Qs"
alias paclorph="sudo pacman -Qdt"
alias pacrorph='sudo pacman -Rs $(pacman -Qtdq)'
alias pacmir="sudo pacman -Syy"
alias pacre="sudo pacman -R"
alias pacrem="sudo pacman -Rns"
alias pacrep="pacman -Si"
alias pacreps="pacman -Ss"
alias pacupd="sudo pacman -Sy && yay -Sy"
alias pacupg="sudo pacman -Syu"
alias pacfileupg="sudo pacman -Fy"
alias pacfiles="pacman -Fs"
alias pacls="pacman -Ql"
alias pacown="pacman -Qo"

paclist() {
	LC_ALL=C pacman -Qei "$(pacman -Qu | cut -d " " -f 1)" | \
		awk 'BEGIN {FS=":"} /^Name/{printf("\033[1;36m%s\033[1;37m", $2)} /^Description/{print $2}'
}

pacdisowned() {
	emulate -L zsh

	# TODO: do we care that UID is not POSIX?
	tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
	db=$tmp/db
	fs=$tmp/fs

	mkdir "$tmp"
	trap 'rm -rf "$tmp"' EXIT

	pacman -Qlq | sort -u > "$db"

	find /bin /etc /lib /sbin /usr ! -name lost+found \
		\( -type d -printf '%p/\n' -o -print \) | sort > "$fs"

	comm -23 "$fs" "$db"
}

pacmansignkeys() {
	emulate -L zsh
	for key in "$@"; do
		sudo pacman-key --recv-keys "$key"
		sudo pacman-key --lsign-key "$key"
		printf 'trust\n3\n' | sudo gpg --homedir /etc/pacman.d/gnupg \
			--no-permission-warning --command-fd 0 --edit-key "$key"
	done
}

# yay
alias yaconf='yay -Pg'
alias yaupg='yay -Syu'
alias yasu='yay -Syu --noconfirm'
alias yain='yay -S'
alias yains='yay -U'
alias yare='yay -R'
alias yarem='yay -Rns'
alias yarep='yay -Si'
alias yareps='yay -Ss'
alias yaloc='yay -Qi'
alias yalocs='yay -Qs'
alias yalst='yay -Qe'
alias yaorph='yay -Qtd'
alias yainsd='yay -S --asdeps'
alias yamir='yay -Syy'

### file browsing
# list files
alias ll="ls -Ahl"

# fast find
ff () {
	find . -name "$1"
}

### file manipulation
# remove
alias rm="rm -rfv"
alias rmi="rm -rfvi"

# copy
alias cp="cp -rfv"

# move
alias mv="mv -fv"
alias mvi="mv -fvi"

### directories
# make directory
alias mkdir="mkdir -pv"

# change directory
alias ..="cd .."

### pattern matchers
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

### tmux
# tmux attach
alias ta='tmux attach -t'
alias tad='tmux attach -d -t'

# tmux session
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'

# tmux kill
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

### tmuxinator
# start
alias txs='tmuxinator start'

# open
alias txo='tmuxinator open'

# new
alias txn='tmuxinator new'

# list
alias txl='tmuxinator list'

### git
# git status
alias g="git status -sb"

# git file manipulation
alias ga="git add"
alias gap="git add --patch"
alias gau="git add --update"
alias gav="git add --verbose"
alias gr="git rm"
alias gm="git mv"

# git branch
alias gb="git branch -v"
alias gba='git for-each-ref --sort=committerdate refs/heads/ --format="%(authordate:short) %(color:red)%(objectname:short) %(color:yellow)%(refname:short)%(color:reset) (%(color:green)%(committerdate:relative)%(color:reset))"'
alias gba='git for-each-ref --sort=-committerdate refs/heads/ --format="%(authordate:short) %(color:red)%(objectname:short) %(color:yellow)%(refname:short)%(color:reset) (%(color:green)%(committerdate:relative)%(color:reset))"'

# git commit
alias gc="git commit"
alias gca="git commit --amend"
alias gcm="git commit -m"

# git checkout
alias gcod="git checkout develop"
alias gcom="git checkout master"
alias gcos="git checkout staging"

# git fetch
alias gf="git fetch"
alias gfa="git fetch --all"

# better git pull
alias gup="git remote update -p; git merge --ff-only @{u}"
alias gupr="git rebase -p @{u}"

# git pull
alias gp="git pull"
alias gpr="git pull --rebase"

# git pull (origin)
alias gpod="git pull origin develop"
alias gpom="git pull origin master"
alias gpos="git pull origin staging"
alias gprod="git pull --rebase origin develop"
alias gprom="git pull --rebase origin master"
alias gpros="git pull --rebase origin staging"

# git pull (upstream)
alias gpud="git pull origin develop"
alias gpum="git pull origin master"
alias gpus="git pull origin staging"
alias gprud="git pull --rebase origin develop"
alias gprum="git pull --rebase origin master"
alias gprus="git pull --rebase origin staging"

# git push (origin)
alias gpsod="git pull origin develop"
alias gpsom="git pull origin master"
alias gpsos="git pull origin staging"
alias gpsrod="git pull --rebase origin develop"
alias gpsrom="git pull --rebase origin master"
alias gpsros="git pull --rebase origin staging"

# git push (upstream)
alias gpsud="git pull origin develop"
alias gpsum="git pull origin master"
alias gpsus="git pull origin staging"
alias gpsrud="git pull --rebase origin develop"
alias gpsrum="git pull --rebase origin master"
alias gpsrus="git pull --rebase origin staging"

# git push (force with lease)
alias gpofl="git push --force-with-lease origin"
alias gpofl="git push --force-with-lease upstream"

# git stash
alias gsl="git stash list"
alias gsp="git stash pop"
alias gss="git stash save"

# git diff/log
alias gd="git diff --color-words"
alias gl="git log --oneline --decorate"
alias gslog="git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"

# git apply
alias gapp="git apply"

# git functions
# TODO

### github
alias git="hub"

# github page
alias gh="git browse -- /"
alias ghi="git browse -- /issues"
alias ghp="git browse -- /pulls"
alias ghw="git browse -- /wiki"

### rest
alias mount="mount | column -t"
alias mexec="chmod a+x"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % "$EDITOR" % ;}
